import { vi } from 'vitest';
import type { Dashboard } from '../lib/api';

const emptyDashboard: Dashboard = {
  identity: {
    handle: '@test',
    title: 'Test Forger',
    current_phase: 'forge',
    proficiency: { aspects: {} },
    workingOn: ['Patience'],
  },
  stats: { aspectCount: 0, tierCounts: [] },
  baseLayer: [{ symbol: '🍁', name: 'Red Leaf', proficiency: 0.5, mantras: [] }],
  activeGoals: [],
  recentRuns: [],
  grok: { loaded: false },
  journal: { loaded: false, entry_count: 0 },
};

export const mockApi = {
  dashboard: vi.fn(async () => emptyDashboard),
  aspects: vi.fn(async () => []),
  aspectFaceIndex: vi.fn(async () => ({ byId: {}, builtAt: '', aspectCount: 0, faceCount: 0 })),
  aspect: vi.fn(async () => {
    throw new Error('not found');
  }),
  synergies: vi.fn(async () => []),
  codex: vi.fn(async () => ({ operators: [], protocols: [], synthesis: [] })),
  axioms: vi.fn(async () => []),
  protocols: vi.fn(async () => []),
  operators: vi.fn(async () => ({})),
  lore: vi.fn(async () => []),
  loreStory: vi.fn(async () => ({ key: '', content: '', source: '' })),
  proficiencyTracks: vi.fn(async () => []),
  forge: vi.fn(async () => ({
    masterAspect: { name: 'Test', symbolChain: '🍁🔥', mantra: 'test', affirmation: 'test', tier: 'B', potential: 0.5 },
    facets: [],
    integration: { operator: 'EOT', saveCodex: 'Save8' },
  })),
  forgeExamples: vi.fn(async () => []),
  eot: vi.fn(async () => ({ routedTool: 'EOT', grade: 'basic' })),
  dailyRuns: vi.fn(async () => []),
  dailyRun: vi.fn(async () => ({ id: 1, run_type: 'DFR', notes: '', created_at: '' })),
  goals: vi.fn(async () => []),
  createGoal: vi.fn(async () => ({ id: 1, title: 'Test', description: '', progress: 0, aspect_link: '', status: 'active' })),
  updateGoal: vi.fn(async () => ({ id: 1, title: 'Test', description: '', progress: 0, aspect_link: '', status: 'active' })),
  deleteGoal: vi.fn(async () => ({ ok: true, id: 1 })),
  achievements: vi.fn(async () => []),
  personas: vi.fn(async () => [
    {
      id: 1,
      name: 'Aspect Forger',
      archetype: 'Creator',
      symbol_chain: '⚒️🍁♾️',
      mantra: 'I forge what I feel into what I become.',
      description: 'Primary operator identity',
      active: 1,
    },
    {
      id: 2,
      name: 'Red Leaf Owl King',
      archetype: 'Watcher',
      symbol_chain: '🍁🦉🌕',
      mantra: 'I watch with moonlit eyes. Patience is my crown.',
      description: 'EverWatcher vigil persona',
      active: 0,
    },
  ]),
  activatePersona: vi.fn(async (id: number) => ({
    id,
    name: 'Activated',
    archetype: 'Test',
    symbol_chain: '🍁',
    mantra: 'test',
    description: 'test',
    active: 1,
  })),
  insights: vi.fn(async () => []),
  techniques: vi.fn(async () => []),
  fusions: vi.fn(async () => []),
  math: vi.fn(async () => []),
  visualizations: vi.fn(async () => []),
  automations: vi.fn(async () => []),
  identity: vi.fn(async () => ({
    handle: '@test',
    title: 'Test',
    bio: '',
    current_phase: 'forge',
    evolution_path: '',
    proficiency: {},
    workingOn: [],
    evolutions: [],
    topAspects: [],
  })),
  search: vi.fn(async () => []),
  grokConversations: vi.fn(async () => []),
  grokConversation: vi.fn(async () => ({ loaded: false })),
  grokSessions: vi.fn(async () => []),
  grokSession: vi.fn(async () => ({ id: '', title: '', messages: [] })),
  grokFiveSymbols: vi.fn(async () => null),
  discordStatus: vi.fn(async () => ({
    configured: false,
    offline: true,
    guild_name: 'AFS (offline)',
    message_count: 2,
    primary_journal_channel: 'journal',
    latest_posted_at: '2025-04-01T12:00:00.000Z',
    latest_channel: 'journal',
  })),
  discordJournal: vi.fn(async () => [
    {
      id: 'local-april1-1',
      guild_id: 'local',
      channel_id: 'local',
      channel_name: 'journal',
      author_id: 'local',
      author_name: 'Madhur',
      content: 'Date: 2025-04-01\nAspect/symbol: 🌪️ Tornado of Momentum\nReflection: Static snapshot entry one.',
      posted_at: '2025-04-01T12:00:00.000Z',
      synced_at: '2025-04-01T12:00:00.000Z',
      journal_type: 'daily',
      tags: [],
      attachments: [],
    },
    {
      id: 'local-april1-2',
      guild_id: 'local',
      channel_id: 'local',
      channel_name: 'journal',
      author_id: 'local',
      author_name: 'Madhur',
      content: 'Date: 2025-04-01\nAspect/symbol: ⚓ Stability Anchor\nReflection: Static snapshot entry two.',
      posted_at: '2025-04-01T11:00:00.000Z',
      synced_at: '2025-04-01T11:00:00.000Z',
      journal_type: 'daily',
      tags: [],
      attachments: [],
    },
  ]),
  syncJournalFromDiscord: vi.fn(async () => ({ synced: 0 })),
  clubJournalEntries: vi.fn(async () => ({ merged: 0 })),
  createJournalEntry: vi.fn(async () => ({ id: '1', content: '', posted_at: '' })),
  updateJournalEntry: vi.fn(async () => ({ id: '1', content: '', posted_at: '' })),
  mergeJournalEntries: vi.fn(async () => ({ id: '1', content: '', posted_at: '' })),
  previewJournalAspects: vi.fn(async () => ({ aspects: [] })),
  syncJournalAspects: vi.fn(async () => ({ synced: 0 })),
  deleteJournalEntry: vi.fn(async () => ({ ok: true })),
  logPomodoro: vi.fn(async () => ({ ok: true })),
  visualizationMediaUrl: vi.fn(() => '/api/media/0'),
  loreMediaUrl: vi.fn(() => '/api/lore/0/media'),
  kernel: vi.fn(async () => {
    const { default: snap } = await import('../lib/red-leaf-kernel-snapshot.json');
    return snap.kernel;
  }),
  kernelNav: vi.fn(async () => {
    const { default: snap } = await import('../lib/red-leaf-kernel-snapshot.json');
    return { seed: '🍁', nav: snap.nav };
  }),
  kernelFlow: vi.fn(async () => {
    const { default: snap } = await import('../lib/red-leaf-kernel-snapshot.json');
    return snap.flow;
  }),
  kernelPulses: vi.fn(async () => ({
    seed: '🍁',
    pulses: [],
    stats: { total: 0, latest: null },
  })),
  kernelPulse: vi.fn(async (from: string, payload?: unknown) => ({
    ok: true,
    event: {
      id: 'mock-pulse',
      seed: '🍁',
      at: new Date().toISOString(),
      origin: from,
      originSymbol: '🍁',
      payload,
      reach: 1,
      hops: 0,
      trace: [{ hop: 0, module: from, symbol: '🍁', via: null, action: 'emit' as const }],
      paradox: '🍁(pulse) = Reframe(network)',
    },
  })),
  kernelReady: vi.fn(async () => ({
    seed: '🍁',
    iteration: 4,
    strategy: {
      title: 'Practical Red Leaf strategy',
      summary: 'Dev tooling first.',
      phases: [],
    },
    observabilityReady: true,
    generationReady: false,
    ready: false,
    requirements: [
      { id: 'runtime-flag', label: 'Runtime generation explicitly enabled', detail: '', pass: false },
    ],
    metrics: { moduleCount: 20, routeCount: 20, unfoldBytes: 50000, unfoldBudgetBytes: 120000 },
    checkedAt: new Date().toISOString(),
  })),
  kernelResolve: vi.fn(async (id: string) => ({
    id,
    symbol: '🍁',
    path: `/${id}`,
    label: id,
    branch: 'seed',
    operator: 'seed',
    operatorSymbol: '🍁',
    vector: 'origin',
    depth: 0,
    glyph: '🍁',
    api: { primary: `/api/${id}`, read: [], write: [] },
    emits: [],
    dataSources: [],
    dataSinks: [],
    flow: { inbound: [], outbound: [] },
  })),
};